#!/bin/bash
# ^^^^^^^^^ bash because it uses "[["

scriptsdir=$PWD

usage() {
    cat <<EOF
Usage: pwx_test_kernel_pkgs [options] pkg_files...
    options:
	--all-releases
	--arch=architecture            [default: amd64]
	--containers=container_system  [default: docker]
	--container-tmpdir=dir       [default: /tmp/test-portworx-kernels.\$\$]
	--distribution=dist            [default: ubuntu]
	--force
        --help
	--leave-containers-running
	--logdir=logdir                [default: based on distribution]
	--pfxuse=pxfuse_src_dir        [default: download tempoary
				        directory from github]
	--prepare-build
	--releases=dist_releases       [default: based on distribution]
	--skip-build
	--skip-cleanup
	--skip-load
EOF
}


. ${scriptsdir}/container_driver.sh
. ${scriptsdir}/distro_driver.sh

all_releases=false
arch=amd64
distro=ubuntu
distro_releases=""
extra_args=""
container_system=lxc
force=false
logdir=$PWD
lockdir=/var/lock/pwx_test_kernel_pkgs
pxfuse_dir=
skip_build=false

exit_handler() {
    rm -rf "$local_tmp_dir"
}

# Use a function to parse main argument to avoid modifying them.
parse_args() {
    local all_args="$*"
    local non_switch_args=0
    while [[ $# -gt 0 ]] ; do
	case "$1" in
	    --all-releases ) all_releases=true ;;
	    --arch=* ) arch=${1#--arch=} ;;
	    --containers=* ) container_system=${1#--containers=} ;;
	    --container-tmpdir=* ) extra_args="$extra_args $1" ;;
	    --distribution=* ) distro=${1#--distribution=} ;;
	    --force ) force=true ;;
	    --help ) usage ; exit 0 ;;
	    --leave-containers-running ) true ;;
	    --logdir=* ) logdir=${1#--logdir=} ;;
	    --pxfuse=* ) pxfuse_dir=${1#--pxfuse=} ;;
	    --prepare-build ) extra_args="$extra_args $1" ;;
	    --releases=* ) distro_release=${1#--releases=} ;;
	    --skip-build ) extra_args="$extra_args $1" ; skip_build=true ;;
	    --skip-cleanup ) extra_args="$extra_args $1" ;;
	    --skip-load ) extra_args="$extra_args $1" ;;
	    -- ) break ;;
	    --* )
		echo "pwx_test_kernel_pkgs: Unrecognized option \"${1}\"." >&2
		usage >&2
		exit 1 ;;
	    * ) non_switch_args=$(($non_switch_args + 1)) ;;
	esac
	shift
    done

    if [[ $non_switch_args -lt 1 ]] ; then
	usage >&2
	exit 1
    fi
}

parse_args "$@"

local_tmp_dir=/tmp/test-kernels.ubuntu.$$

prepare_pxfuse_dir() {
    trap exit_handler EXIT

    mkdir -p "$local_tmp_dir"
    if [[ -z "$pxfuse_dir" ]] ; then
	(cd "$local_tmp_dir" &&
	 git clone https://github.com/portworx/px-fuse.git )

	pxfuse_dir="$local_tmp_dir/px-fuse"
	# ^^^^^^^ Global variable.
    fi
}

match_word() {
    local small=$1
    local big

    shift
    for big in "$@" ; do
	case "$big" in
	    *"${small}"* ) return 0 ;;
	esac
    done
    return 1
}


matches_first() {
    local releases="$1"
    local file first unmatched
    unmatched=""

    shift

    # Skip command options to get to path names
    while true ; do
	case "$1" in
	    -- ) shift ; break ;;
	    --* ) shift ;;
	    * ) break ;;
	    esac
    done

    for release in $releases ; do
	if match_word "$release" "$@" ; then
	    echo "$release"
	else
	    unmatched="$unmatched $release"
	fi
    done
    echo $unmatched
}

test_kernel_pkgs() {
    local result release releases local make_args lockfile

    if [[ -n "$distro_releases" ]] ; then
	releases=$(echo "$distro_releases" | sed 's/,/ /g')
    else
	releases=$(get_dist_releases)
    fi

    mkdir -p "$lockdir"

    result=1 # in case one of the loops should be empty for some reason.

    # The use of matches_first is an optimization that first tries operating
    # system releases that appear somewhere in the paths of the package
    # files being tested.  For Centos, which has releases like "6"
    # and "7", this probably has little effect, but for Fedora, which
    # is up in the two digits, and the Debian-based distributions that
    # use names, it may be a more substantial improvement.
    for release in $(matches_first "$releases" "$@") ; do
	for make_args in "" "CC=\"gcc -fno-pie\"" ; do
	    lockfile="$lockdir/container_${container_system}_${distro}_${release}"
	    touch -f "$lockfile"
	    flock --exclusive --close "$lockfile" \
		  $scriptsdir/pwx_test_kernel_pkgs_one_container.sh \
			"--pxfuse=$pxfuse_dir" \
			"--release=$release" \
			"--make-args=$make_args" \
			$extra_args \
			"$@"

	    result=$?

	    if [[ $result = 0 ]] ; then
		break
	    fi
	done
	if [[ $result = 0 ]] && ! $all_releases ; then
	    break
	fi
    done
    if ! $skip_build ; then
	echo "$result $distro $release make_args=$make_args" > "$logdir/exit_code"
	mv "$logdir/ran_test" "$logdir/done" 2> /dev/null
    fi
    return $result
}

main()
{
    if [[ -e "$logdir/done" ]] && ! $force ; then
	echo "test_kernel_pkgs: $logdir/done exists.  Skipping."
    else
	prepare_pxfuse_dir
	mkdir -p "$logdir"
	rm -f "$logdir/ran_test"
	test_kernel_pkgs "$@" > "$logdir/build.log" 2>&1
    fi
}

main "$@"

