#!/bin/bash
# ^^^^^^^^^ bash because it uses "[["

scriptsdir=$PWD

usage() {
    cat <<EOF
Usage: pwx_test_kernel_pkgs [options] pkg_files...
    options:
	--arch=architecture            [default: amd64]
	--containers=container_system  [default: docker]
	--distribution=dist            [default: ubuntu]
	--force
        --help
	--leave-containers-running
	--logdir=logdir                [default: based on distribution]
	--pfxuse=pxfuse_src_dir        [default: download tempoary
				        directory from github]
	--releases=dist_releases       [default: based on distribution]
EOF
}


. ${scriptsdir}/container_driver.sh
. ${scriptsdir}/distro_driver.sh

arch=amd64
distro=ubuntu
distro_releases=""
container_system=lxc
force=false
logdir=$PWD
lockdir=/var/lock/pwx_test_kernel_pkgs
pxfuse_dir=

exit_handler() {
    rm -rf "$local_tmp_dir"
}

# Use a function to parse main argument to avoid modifying them.
parse_args() {
    while [[ $# -gt 0 ]] ; do
	case "$1" in
	    --arch=* ) arch=${1#--arch=} ;;
	    --containers=* ) container_system=${1#--containers=} ;;
	    --distribution=* ) distro=${1#--distribution=} ;;
	    --force ) force=true ;;
	    --help ) usage ; exit 0 ;;
	    --leave-containers-running ) true ;;
	    --logdir=* ) logdir=${1#--logdir=} ;;
	    --pxfuse=* ) pxfuse_dir=${1#--pxfuse=} ;;
	    --releases=* ) distro_release=${1#--releases=} ;;
	    --* ) usage >&2 ; exit 1 ;;
	    * ) break ;;
	esac
	shift
    done

    if [[ $# -lt 1 ]] ; then
	usage >&2
	exit 1
    fi
}

parse_args "$@"

local_tmp_dir=/tmp/test-kernels.ubuntu.$$

prepare_pxfuse_dir() {
    trap exit_handler EXIT

    mkdir -p "$local_tmp_dir"
    if [[ -z "$pxfuse_dir" ]] ; then
	(cd "$local_tmp_dir" &&
	 git clone https://github.com/portworx/px-fuse.git )

	pxfuse_dir="$local_tmp_dir/px-fuse"
	# ^^^^^^^ Global variable.
    fi
}

test_kernel_pkgs() {
    local result release releases local make_args lockfile

    echo "Command: pwx_test_kernel_pkgs $*"

    if [[ -n "$distro_releases" ]] ; then
	releases=$(echo "$distro_releases" | sed 's/,/ /g')
    else
	releases=$(get_dist_releases)
    fi

    mkdir -p "$lockdir"

    result=1 # in case one of the loops should be empty for some reason.

    for make_args in "" "CC=\"gcc -fno-pie\"" ; do
	for release in $releases ; do
	    lockfile="$lockdir/container_${container_system}_${distro}_${release}"
	    touch -f "$lockfile"
	    flock --exclusive --close "$lockfile" \
		  $scriptsdir/pwx_test_kernel_pkgs_one_container.sh \
			"--pxfuse=$pxfuse_dir" \
			"--release=$release" \
			"--make-args=$make_args" \
			$@

	    result=$?

	    if [[ $result = 0 ]] ; then
		break
	    fi
	done
	if [[ $result = 0 ]] ; then
	    break
	fi
    done
    echo "$result $distro $release make_args=$make_args" > "$logdir/exit_code"
    mv "$logdir/ran_test" "$logdir/done" 2> /dev/null
    return $result
}

main()
{
    if [[ -e "$logdir/done" ]] && ! $force ; then
	echo "test_kernel_pkgs: $logdir/done exists.  Skipping."
    else
	prepare_pxfuse_dir
	mkdir -p "$logdir"
	rm -f "$logdir/ran_test"
	test_kernel_pkgs "$@" > "$logdir/build.log" 2>&1
    fi
}

main "$@"

